---
- hosts: localhost
  connection: local
  become: true
  vars_files: ../allvars.yml
  
  vars_prompt:
    - name: "qcow2_url"
      prompt: "RHEL QCOW2 url"

  tasks:

    - get_url:
        url: "{{ qcow2_url }}"
        dest: /root/images/rhel-server.qcow2
        checksum: sha256:ce4943d38e00a5c81272ebd3f3542b2d9557382d1c331c46ed553fdcca778b2d
        owner: qemu
        group: qemu
