---
- name: Sysctl params
  hosts: localhost
  connection: local
  become: yes
  vars_files: ../allvars.yml
  
  tasks:
    - template:
        src: templates/sysctl_kvm_intel.yml
        dest: /etc/modprobe.d/kvm_intel.conf
      notify: restart vbmcd


    - sysctl:
        name: "{{ item.param }}"
        value: "{{ item.val }}"
        sysctl_file: /etc/sysctl.d/98-rp-filter.conf
        sysctl_set: yes
        reload: yes
      loop: "{{ sysctl_vars }}"

# Stop a network
    - virt_net:
        command: destroy
        name: default


# Add a new host in the dhcp pool
    - virt_net:
        name: default
        command: modify
        xml: >
          <host mac='52:54:00:7a:e1:64' name='master1' ip='192.168.122.21'/>
          <host mac='52:54:00:30:66:8d' name='master2' ip='192.168.122.22'/>
          <host mac='52:54:00:74:96:ce' name='master3' ip='192.168.122.23'/>
          <host mac='52:54:00:74:dd:bb' name='worker1' ip='192.168.122.31'/>
          <host mac='52:54:00:e4:e6:e6' name='worker2' ip='192.168.122.32'/>

# Start a network
    - virt_net:
        command: create
        name: default   

  handlers:
    - name: restart vbmcd
      systemd:
        name: vbmcd
        state: restarted
        enabled: yes
