---
- name: Sysctl params
  hosts: localhost
  connection: local
  become: yes
  vars_files: ../allvars.yml
  
  tasks:
  
  # Add the kvm_intel modprobe  params.
    - template:
        src: /root/virt_ocp/templates/sysctl_kvm_intel.yml
        dest: /etc/modprobe.d/kvm_intel.conf
      notify: restart vbmcd

# Configure the sysctl params
    - sysctl:
        name: "{{ item.param }}"
        value: "{{ item.val }}"
        sysctl_file: /etc/sysctl.d/98-rp-filter.conf
        sysctl_set: yes
        reload: yes
      loop: "{{ sysctl_vars }}"
    
# Enable and start the libvirtd service    
    - systemd:
        name: libvirtd
        state: started
        enabled: yes

# Stop the default network
    - virt_net:
        command: destroy
        name: default


# Add a static IPs in the dhcp pool
    - virt_net:
        name: default
        command: modify
        xml: "{{ multi_pattern }}"

# Start the default network
    - virt_net:
        command: create
        name: default   

  handlers:
    - name: restart vbmcd
      systemd:
        name: vbmcd
        state: restarted
        enabled: yes
