---
- name: Sysctl params
  hosts: localhost
  connection: local
  become: yes
  vars_files: allvars.yml
  tasks:
    - template:
        src: templates/sysctl_kvm_intel.yml
        dest: /etc/modprobe.d/kvm_intel.conf
      notify: restart vbmcd


    - sysctl:
        name: "{{ item.param }}"
        value: "{{ item.val }}"
        sysctl_file: /etc/sysctl.d/98-rp-filter.conf
        sysctl_set: yes
        reload: yes
      loop: "{{ sysctl_vars }}"




  handlers:
    - name: restart vbmcd
      systemd:
        name: vbmcd
        state: restarted
        enabled: yes
